### ISSUE TITLE
Issue with locking accounts

### ISSUE THREAD

**Issue by 7b7bruno** [Quessts/Snapify#5]
Hi, I had my account locked when I used the add friends feature. This could be a major issue if there isn't already a way to solve It. If there is, please comment with the solution.

**Comment by Quessts** [comment]
Hey, so if you add too many friends at once Snapchat may lock you. But, it's just a temporary lock to prevent spam. You can prevent this from happening by verifying your account (add and confirm both your email and phone number). It's also very easy to unlock just click [here](https://accounts.snapchat.com/accounts/unlock), log into your account and click the unlock button.
